require('./main.css');
require('./main.scss');
var sub = require('./sub');
var $ = require('jquery');
var moment = require('moment');
var app = document.createElement('div');
app.innerHTML = '<h1>Hello world</h1>';
app.appendChild(sub());
$('body').append('<p> look at me! now is ' + moment().format() + '</p>');
document.body.appendChild(app);